name: build-and-deploy-on-droplet
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.11.4'
      - name: Install Dependencies
        run: pip install -r requirements.TXT
      - name: Run tests
        run: pytest
  deploy-on-droplet:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: ssh-setup
        run: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            touch ~/.ssh/id
            echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id
            chmod 600 ~/.ssh/known_hosts
            chmod 600 ~/.ssh/id
            chmod 700 ~/.ssh
      - run: ls
      - name: send commands
        run : ssh -tt -i ~/.ssh/id root@${{ secrets.SSH_HOST }} "bash -s" < commands.sh && exit