name: build-and-deploy-on-droplet
on: 
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: 174.138.12.66
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}{% endraw%} >> ~/.ssh/known_hosts
      - name: send commands
        run : ssh -tt -i ~/.ssh/id root@${{ secrets.SSH_HOST }} "bash -s" < commands.sh && exit