name: Print Hello

on: workflow_dispatch
jobs:
  print-hello:
    # Specify on which operating system we want this workflow to run
    runs-on: ubuntu-20.04
    # The steps that will be executed
    steps:
    - name: Print
      run: echo "Hello, world! I'm almost there with this last assignment from Winc Academy!"
