name: Run Tests

on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python 3.11.4
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: python -m pytest